// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import MapController from "./map_controller"
import SpecialityController from "./speciality_controller"
import TypedJsController from "./typed_js_controller"
import NavbarController from "./navbar_controller.js"
application.register("hello", HelloController)
application.register("map", MapController)


application.register("navbar", NavbarController)


application.register("speciality", SpecialityController)


application.register("typed-js", TypedJsController)


application.register("navbar", NavbarController)
